version: '2'

services:
  acr-mysql:
    container_name: acr-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3306:3306"
    restart: always

  acr-app:
    container_name: acr-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - acr-mysql
    command: ["./wait-for-it.sh", "db:3306", "--", "python3", "mysql-test.py"]
    ports:
      - "8181:8181"
    restart: always